services:
  backend:
    build:
      context: ./partiw-back/api
      dockerfile: Dockerfile
    image: meu-backend:1.0 # Nome e tag da imagem para o backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./partiw-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
