services:
  backend:
    build:
      context: ./partiw-back/api
      dockerfile: Dockerfile
    image: mvp-partiw-backend:1.1
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./partiw-front
      dockerfile: Dockerfile
    image: mvp-partiw-frontend:1.1
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
